### ISSUE TITLE
Unpulled/Unpushed changes arrow

### ISSUE THREAD

**Issue by peduarte** [brandonweiss/pure.fish#2]
Hi 🙂 Love your theme, thank you!

However I cannot see the up/down arrow for unpushed/unpulled changes.
I haven't changed anything.

Do you know why?

Thanks!

**Comment by brandonweiss** [comment]
Hey! Well, it's pretty difficult to debug remotely… these might seem obvious, but double-check you're in a git repo. Double-check you're on a branch that also exists on a remote. Double-check you've fetched recent refs. Beyond that I'm not sure. You'll have to go spelunking and try out the commands to see what they return and if they're returning something unexpected 😬

**Comment by peduarte** [comment]
@brandonweiss hey man, no worries, yeah it's a bit tricky. I did check all of those.
I also went through other prompts to see how they did it and it seems like everyone has a different approach. I do prefer the way you did it though as I find it the most readable.

To expand a bit on the issue: it works "sometimes". I'm thinking maybe it's not a bug, but rather, this is just a pretty simple implementation. I think maybe the issue is, the `up` arrow doesn't show unless I've pushed it at least once?

**Comment by brandonweiss** [comment]
Yes, that's right, if you're on a branch, and you haven't pushed it to a remote, then it would have nothing to compare against. I suppose if there's a way to determine that a branch is unpushed, we could do that and show the up arrow? I'm a little swamped at the moment but if you want to make a PR that would be awesome!

**Comment by peduarte** [comment]
I will if I find a better solution, will close for now. Thanks!
